### PR TITLE
Add stop method to Makefile

### PR DESCRIPTION
**Pull request by mkly**

### CODE REVIEW

**Comment by mkly** [comment]
Really enjoying this. Thanks a lot for putting it together. I just added a stop method to the Makefile. It might be overkill as you can do all the usual `docker-compose` commands without the Makefile. Feel free to close it if you feel that way. Either way this is awesome.

Regards,
Mike :tropical_drink:

**Comment by alcalyn** [comment]
Thanks, glad you enjoy it !

**Comment by alcalyn** [comment]
Did you install the edition with `composer create-project` ? If yes, I didn't released for a while, and just released now with the latest feature, see changelog: https://github.com/eole-io/sandstone-edition/releases/tag/1.2.5

You can test if you have the last version by running `make book` in your current edition, it should display links.

**Comment by mkly** [comment]
I followed the directions for the Docker instalation provided by the docs
https://eole-io.github.io/sandstone-doc/edition/get-started#docker-installation
`curl -L https://github.com/eole-io/sandstone-edition/archive/dev.tar.gz | tar xz`
Which I believe ends up pulling from the dev branch.

**Pull request merged**
